[package]
authors = ["Anthony MOI <m.anthony.moi@gmail.com>"]
edition = "2018"
name = "tokenizers-lib"
version = "0.0.1"
[[bin]]
name = "cli"
path = "src/cli.rs"

[dependencies]
lazy_static = "1.3.0"
onig = "5.0.0"
rayon = "1.2.0"
serde_json = "1.0"

[lib]
name = "tokenizers"
path = "src/lib.rs"
